apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  labels:
    app: service-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      name: service-1
      labels:
        app: service-1
    spec:
      containers:
        - name: service-1
          image: kparavindbabu/containerorchestration.api
          env:
            - name: InternalServiceSettings__Url
              value: http://service-2.default.svc.cluster.local:8802
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
  labels:
    app: service-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      name: service-2
      labels:
        app: service-2
    spec:
      containers:
        - name: service-2
          image: kparavindbabu/containerorchestration.api
          env:
            - name: InternalServiceSettings__Url
              value: http://service-1.default.svc.cluster.local:8801
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
      