apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app: service-1
  ports:
    - protocol: TCP
      port: 8801
      targetPort: 8080
 # type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
  selector:
    app: service-2
  ports:
    - protocol: TCP
      port: 8802
      targetPort: 8080
 # type: LoadBalancer
