apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo-app
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: $1
spec:
  ingressClassName: nginx
  rules:
    - # host: kubernetes.docker.internal # enable this line to restrict the following services only accessed from this host name
      http: 
        paths:
          - path: /s1(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-1
                port:
                  number: 8801
          - path: /s2(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-2
                port:
                  number: 8802
